#server:
#  port: 9090
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/SocialMediaAuthDB
#    username: postgres
#    password: Bm15481527
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#jwt:
#  secretkey: ${secretkey}
#  audience: ${audience}
#  issuer: ${issuer}

spring:
  cloud:
    config:
      uri: ${CONFIG_GIT}  #http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: auth-service-application