#server:
#  port: 8070
#spring:
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: post-service
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: userprofileDB
#      username: JavaUser
#      password: root
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: java7
#    password: root
#jwt:
#  secretkey: ${secretkey}
#  audience: ${audience}
#  issuer: ${issuer}
spring:
  cloud:
    config:
      uri: ${CONFIG_GIT} #http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: post-service-application